[development]
log_level = "debug"
address = "127.0.0.1"
port = 8081

[production]
log_level = "critical"
address = "127.0.0.1"
port = 8081

[global.databases]
sqlite = {url = "./database/testing_db.db"}
