[development]
log_level = "debug"
address = "127.0.0.1"
port = 8081
jwt_secret = "my very super secret"

[development.databases]
sqlite = {url = "./database/testing_db.db"}

[production]
log_level = "critical"
address = "127.0.0.1"
port = 8081
jwt_secret = ""

[production.databases]
sqlite = {url = "./database/production_db.db"}
