max_width = 80
reorder_imports = true
imports_granularity = "Crate"
format_code_in_doc_comments=true
doc_comment_code_block_width = 80
format_strings = true
match_block_trailing_comma = true
normalize_comments = true
reorder_impl_items = true
struct_lit_single_line = false
tab_spaces = 2
wrap_comments = true
